### ISSUE TITLE
several thermostats with a single heater

### ISSUE THREAD

**Issue by jmora0** [custom-components/climate.programmable_thermostat#20]
How would it be possible to configure the related_climate if there are several devices with their respective temperatures and only one heater?

**Comment by alextircovnicu** [comment]
Hi 
+1 from my side.

The setup will be as following:
- 1 heating boiler  -> switch.hb
- Room 1
    - valve 1  -> switch.v1_1
    - valve 2  -> switch.v1_2
    - temperature -> sensor.t1  
- Room 2
    - valve 1  -> switch.v2_1
    - valve 2  -> switch.v2_2
    - temperature -> sensor.t2  
- Anything else
    -temperature 1 -> sensor.t3  
    -temperature 2 -> sensor.t4  
    -temperature 3 -> sensor.t5 
    -temperature 4 -> sensor.t6  


Desired output (currently achieved via automation)  for keeping ambient temperature to 21 degrees : 
WHEN  sensor.t1 < 21  
THEN turn ON  switch.v1_1 
AND  turn ON switch.v1_2
AND  turn ON switch.hb 

WHEN  sensor.t2 < 21  
THEN turn ON  switch.v2_1 
AND  turn ON switch.v2_2
AND  turn ON switch.hb 

WHEN  any of sensor.t[3-6] < 21  
THEN  turn ON switch.hb 

WHEN  t1 >= 21  
THEN turn OFF switch.v1_1 
AND turn OFF  switch.v1_2 

WHEN  t2 >= 21  
THEN turn OFF switch.v2_1 
AND turn OFF  switch.v2_2 

WHEN  All temperature sensors t[1-6]  >= 21
THEN turn OFF switch.hb

**Comment by MapoDan** [comment]
Ciao guys,
This is already partially achieved.
I mean, this integration is to control room temperature not the heater.
As heater and cooler switch I meant the 'object' that allows to manage the room temperature, so in your case the valve. Then you have to separately manage the real heater switch with the automation you need since anyone can have a different rule.

In my case for example I have:
- Room from 1 to 7:
  - switch.valve_x (with x 1-7)
  - sensor.temp_room_x (with x 1-7)
- Room 8:
  - switch.valve_1
  - sensor.temp_room_8
- Heater (shared between all rooms)
  - switch.heater

So I have the following objects definded:
- 6 climates for room 2-6
- 1 climate for room 1 with related_climate=room 8
- 1 climate for room 8 with related_climate=room 1
- 1 automation that turns on heater when ONE climate turns on (with some delay due to how it works)
- 1 automation that turns off heater when ALL climates are off

Implementing something static in the climate would be possible, but it wouold limit the possibilities since your case has some rules, mine has others, and so on..

So my suggestion is:
- Define a climate per room each of it with the room valve switches.
- Define a climate related to each temp sensor not in the rooms using input bool as helpers.
- Define atutomation related to valve switches and input booleans to turn on and off the heater switch.

Let me know

**Comment by MapoDan** [comment]
Closed for inactivity.
