### ISSUE TITLE
[Feature Request] Compatibility with Heat and Cool provided by same device

### ISSUE THREAD

**Issue by koldogut** [custom-components/climate.programmable_thermostat#32]
Aerothermal systems are composed by a heat/cool pump and a water circuit (hose - coils) under the floor. It provides hot water in winter and cool water in summer (big tank in the basement) to heat or chill the floor. Heat or Chill mode is set in a central console and pumps (1 per plant) are activated with wired thermostats that turns on / off plant's circuit. Thermostat and central console must be set manually in every season to "summer / winter"

I've managed to integrate the central console in HA with curl and web-scrapping (tough, but it works). The point now is to by-pass the fisic thermostats using this programmable Thermostat (cool by the way, thank you for your work), but since cooling and heating device is the same (the relay wired to every pump-contactor where the fisic thermostat also is attached) it prompts the error described in post [https://github.com/custom-components/climate.programmable_thermostat/issues/31#issue-766563563](url)

I can set a complex script to create independent entities mixing HVAC mode set-point and Turn On and Off in order to make this custom thermostat work, but I think it could be easier to not toogle entities (stop cooling device prior to start heating one, which makes all the sense but not for this use-case) if they are the same.

Thank you in advance

**Comment by MapoDan** [comment]
Ciao,

Thanks for the clear description and I think that can be done, but I have one question. You will keep changing manually the season, so no necessity to consider that? if not, how do you plan to manage it? Will you have it in HA?

One very easier workaround in the mean time could be:
- create 2 separate thermostat in HA, one with only cooling mode and one with only heating mode (set only one between `heating `and `cooling`)
- create an automation with a `input_boolean` or a `input_select` that set to `heat_cool` one thermostat e to `off` the other when set to summer and vice versa when set to winter.

Let me know for the questions above and let me know if the temporary workaround works.
Ciao
Daniele

**Comment by koldogut** [comment]
Hey Mapo, sorry for the delay and happy new year! My idea was to use the thermostat to change manually the season; (ie. when any floor set to cold I can trigger to send a curl command to the central console and update the value to Summer). 

Meanwhile, what I've done is to create virtual devices for cooling and heating pointing to the same entity using helpers but is "kinda tricky" and would prefer something simpler, I'll take a look nevertheless to your suggestion but it reduces the choice to use a single thermostat as stated in the example above, I'm afraid.

If you need any testing please let me know.

**Comment by MapoDan** [comment]
Ciao!
Happy new year to you too!
I've just published a new release v7.6.
What it will do is managing the same list of entities for heaters and coolers and manage it in the right way!
This will work only in manual mode, so I suggest to disable heat_cool mode setting hvac_option=3 in the configuration.

I made some test and it seems to work.
What I think that can be added  or managed differently:
- add a new option to run a service to switch between modes and the device (this may allow you to define a script that is run when a climate mode is switched and it will change mode on all the others climates and run other commands like the curl command on your side)
- transform heat and cool mode in automatic mode if an other specfic option is set. This will allow to have them as automatic mode the 2 modes so they can follow a temp plan (use heat_cool mode I think that is not good since you can't continusly switch your device between heat and cool)

Tell me if this version is working as you expect and tell me what you think of the 2 improvement I explained above.
First one should be not too complex, the second one needs some important changes.

Ciao

**Comment by koldogut** [comment]
Hi Mapo, I've been running new version for a couple of days and it seems to be working fine; no errors in logs and pumps are activated correctly. 

Regarding your points my comments below:

- Since you can control climate entities states (off, heat, cool, etc..) you can trigger an automation to set all the thermostats to the same status with the service `climate.set_hvac_mode` , thus, no new functionalities are needed if I'm not wrong.

- The automatic mode to switch between Heat and Cool is gonna be more complex, In my case water tank must change from hot water (40ºC) to cold water (8ºC) and can't switch instantly; is something you do twice a year and is intended to be done manually despite I've integrated it with homeassistant.

**Comment by MapoDan** [comment]
Closing issue since feature has been added and it is working.
