### ISSUE TITLE
target_temp_sensor

### ISSUE THREAD

**Issue by brucysNZ** [custom-components/climate.programmable_thermostat#4]
Hi All
I do not understand what is meant for the Target Temperature. It seems if requires some sort of file or .txt file of which I do not understand 1. what it is and 2. how to format or write such file
I have installed the custom add-on though home assistant HACS
The files have appeared in the custom_components folder
Here is error I am getting at reboot

Error while setting up platform programmable_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/programmable_thermostat/climate.py", line 82, in async_setup_platform
    target_sensor_entity_id, cold_tolerance,hot_tolerance, initial_operation_mode)])
  File "/config/custom_components/programmable_thermostat/climate.py", line 103, in __init__
    self._target_temp = float(hass.states.get(target_sensor_entity_id).state)
ValueError: could not convert string to float: 'unknown'

please help - Thanks

**Comment by brucysNZ** [comment]
Also. the Climate Entity is not showing in States Dev Tools

**Comment by MapoDan** [comment]
Ciao, sorry for the late reply, but I didn't saw your issue.

Target Temperature is the temperature that you want to reach with your heating/cooling system.
On this components the Target temperature has to be an entity that return in state the temperature to reach.
I suggest you to use my other custom components 'file_restore'. This generates a sensor that read a txt file (the you can write with the notify platform) and return a temperature that change every hour in a week.
In this way you can make your heating/cooling system follow the temperature path that you programmed. so you can make the heating/cooling system turn off automatically when you are out of home and make you find the house warm or cold as soon as you are at home.

Instead, if you want to set a static temperature for the whole day/week, it is better to use the official 'Generic Thermostat' from HA team.

(You wasn't able to find in the state machine because of the setup error)

Let me know if you keep have the issue.
