### ISSUE TITLE
When in automatic mode you change the temperature, keep it for a determined amount of time

### ISSUE THREAD

**Issue by gdistasi** [custom-components/climate.programmable_thermostat#51]
If I understand correctly, when you are in automatic mode, you can change the target temperature by hand, in the UI. At that point, that temperature becomes the setting forever.
It would be useful instead to have an option to set the duration of such a new setting. After that duration, the climate would go back to the automatic mode (and the relative temperature).
Indeed, as it is now, it's not clear what's the purpose of the manual mode, since you can change the temperature anyway and that temperature becomes the new one indefinitely.

**Comment by gdistasi** [comment]
On a different note, if things remain as they are now, it woudl be nice if when I set a temperature and the climate is in automatic mode it would go in manual mode (by highlithing the central icon in the UI).

**Comment by MapoDan** [comment]
Ciao,
It is not like that.
- heat_cool is automatic, so it use the target sensor temperature to set the room temperature. You can change it, but it will rollback to the sensor value when it changes. This means that, if the sensor is never change its value the manually set temperature will never go away.
- heat and cool mode are manual. You can change manually the temperature, but in this mode it will never rollback.

This is working like that since everything is based on the tracking changes of HA.
Maybe there is other ways, but I'm really a basic developer :) (sorry)

Daniele
