### ISSUE TITLE
Can't edit thermostat and is causing yaml errors

### ISSUE THREAD

**Issue by jkosharek** [custom-components/climate.programmable_thermostat#68]
I can create a new thermostat and it works, but get yaml check erros: 
'Failed to call service programmable_thermostat/reload. Integration 'l' not found.'
or times
Failed to call service programmable_thermostat/reload. Integration 'c' not found.

If I edit the thermostat I get this error:
User input malformed: expected str for dictionary value @ data['heater']

Can delete the thermostat and the errors go away, create it with the same devices, it creates ok then back to the errors above.

**Comment by Hiekkaharju** [comment]
The edit issue is due to Programmable Thermostat not properly managing existing settings in the configuration flow. You will need to re-entry SOME of the values each time you re-configure, Read the error text for which is missing - the first one shown in your quote is the heater switch entity. Some empty fields require you to insert text "null"

**Comment by MapoDan** [comment]
Ciao,

as said by Hiekkaharju, the config_flow is not done in the perfect way and I found only the workaround to put null when you want to leave the field empty. If you do so, it will work.

For the reload issue it is solved in latest release 8.3
